name: py11
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.0.3
  - scikit-learn=1.2.2
  - pyarrow=11.0.0
  - numpy=1.23.5
  - matplotlib=3.7.1
  - pip
  - pip:
      - prefect==2.10.4
      - tqdm==4.65.0
      - requests==2.31.0
      - joblib==1.3.1
      - psycopg==3.1.10
      - psycopg-binary==3.1.10
      - evidently==0.3.2
      - anyio==3.6.2
